version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: quoriumagro-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: quoriumagro
      POSTGRES_PASSWORD: quoriumagro
      POSTGRES_DB: quoriumagro
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U quoriumagro']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: quoriumagro-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: quoriumagro-meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_ENV: development
    ports:
      - '7700:7700'
    volumes:
      - meilisearch_data:/meili_data
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--spider', 'http://localhost:7700/health']
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: quoriumagro-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
  meilisearch_data:
  redis_data:
