// Comprehensive seed data inspired by nurserylive.com

export const categories = [
  // Main Categories
  {
    name: 'Plants',
    slug: 'plants',
    description: 'Wide variety of indoor and outdoor plants',
    image: '/categories/plants.jpg',
    children: [
      { name: 'Indoor Plants', slug: 'indoor-plants', description: 'Best plants for indoor spaces' },
      { name: 'Outdoor Plants', slug: 'outdoor-plants', description: 'Plants for gardens and balconies' },
      { name: 'Flowering Plants', slug: 'flowering-plants', description: 'Beautiful flowering varieties' },
      { name: 'Medicinal Plants', slug: 'medicinal-plants', description: 'Plants with medicinal properties' },
      { name: 'Cactus & Succulents', slug: 'cactus-succulents', description: 'Low maintenance desert plants' },
      { name: 'Air Purifying Plants', slug: 'air-purifying-plants', description: 'Plants that clean the air' },
      { name: 'Lucky Plants', slug: 'lucky-plants', description: 'Plants that bring good fortune' },
      { name: 'Bonsai Plants', slug: 'bonsai-plants', description: 'Miniature tree art' },
      { name: 'Climbers & Creepers', slug: 'climbers-creepers', description: 'Vertical growing plants' },
      { name: 'Hanging Plants', slug: 'hanging-plants', description: 'Perfect for hanging baskets' },
    ],
  },
  {
    name: 'Seeds',
    slug: 'seeds',
    description: 'High quality seeds for your garden',
    image: '/categories/seeds.jpg',
    children: [
      { name: 'Vegetable Seeds', slug: 'vegetable-seeds', description: 'Grow your own vegetables' },
      { name: 'Flower Seeds', slug: 'flower-seeds', description: 'Colorful flower varieties' },
      { name: 'Herb Seeds', slug: 'herb-seeds', description: 'Fresh herbs for your kitchen' },
      { name: 'Fruit Seeds', slug: 'fruit-seeds', description: 'Grow your own fruits' },
      { name: 'Microgreens Seeds', slug: 'microgreens-seeds', description: 'Nutrient-rich microgreens' },
    ],
  },
  {
    name: 'Pots & Planters',
    slug: 'pots-planters',
    description: 'Stylish containers for your plants',
    image: '/categories/pots.jpg',
    children: [
      { name: 'Ceramic Pots', slug: 'ceramic-pots', description: 'Premium ceramic planters' },
      { name: 'Plastic Pots', slug: 'plastic-pots', description: 'Durable plastic containers' },
      { name: 'Metal Planters', slug: 'metal-planters', description: 'Modern metal designs' },
      { name: 'Hanging Planters', slug: 'hanging-planters', description: 'Wall and ceiling planters' },
      { name: 'Self Watering Pots', slug: 'self-watering-pots', description: 'Automated watering system' },
      { name: 'Garden Pots', slug: 'garden-pots', description: 'Large outdoor containers' },
    ],
  },
  {
    name: 'Fertilizers & Soil',
    slug: 'fertilizers-soil',
    description: 'Nutrition for healthy plant growth',
    image: '/categories/fertilizers.jpg',
    children: [
      { name: 'Organic Fertilizers', slug: 'organic-fertilizers', description: 'Natural plant nutrition' },
      { name: 'Chemical Fertilizers', slug: 'chemical-fertilizers', description: 'Quick-acting nutrients' },
      { name: 'Potting Soil', slug: 'potting-soil', description: 'Ready-to-use soil mix' },
      { name: 'Compost', slug: 'compost', description: 'Organic compost' },
      { name: 'Cocopeat', slug: 'cocopeat', description: 'Coco fiber medium' },
      { name: 'Vermicompost', slug: 'vermicompost', description: 'Worm compost' },
    ],
  },
  {
    name: 'Garden Tools',
    slug: 'garden-tools',
    description: 'Essential tools for gardening',
    image: '/categories/tools.jpg',
    children: [
      { name: 'Hand Tools', slug: 'hand-tools', description: 'Small gardening tools' },
      { name: 'Watering Tools', slug: 'watering-tools', description: 'Watering cans and sprayers' },
      { name: 'Pruning Tools', slug: 'pruning-tools', description: 'Scissors and shears' },
      { name: 'Digging Tools', slug: 'digging-tools', description: 'Spades and shovels' },
      { name: 'Garden Gloves', slug: 'garden-gloves', description: 'Protective gloves' },
    ],
  },
  {
    name: 'Accessories',
    slug: 'accessories',
    description: 'Enhance your gardening experience',
    image: '/categories/accessories.jpg',
    children: [
      { name: 'Plant Stands', slug: 'plant-stands', description: 'Display your plants' },
      { name: 'Garden Decor', slug: 'garden-decor', description: 'Decorative items' },
      { name: 'Bird Feeders', slug: 'bird-feeders', description: 'Attract birds to your garden' },
      { name: 'Garden Lights', slug: 'garden-lights', description: 'Outdoor lighting' },
      { name: 'Trellises', slug: 'trellises', description: 'Support for climbing plants' },
    ],
  },
  {
    name: 'Pest Control',
    slug: 'pest-control',
    description: 'Protect your plants from pests',
    image: '/categories/pest-control.jpg',
    children: [
      { name: 'Organic Pesticides', slug: 'organic-pesticides', description: 'Natural pest control' },
      { name: 'Chemical Pesticides', slug: 'chemical-pesticides', description: 'Strong pest control' },
      { name: 'Fungicides', slug: 'fungicides', description: 'Prevent fungal diseases' },
      { name: 'Neem Products', slug: 'neem-products', description: 'Neem-based solutions' },
    ],
  },
];

export const products = [
  // Indoor Plants
  {
    name: 'Money Plant (Pothos)',
    slug: 'money-plant-pothos',
    categorySlug: 'indoor-plants',
    description: 'Easy to grow indoor plant that purifies air and brings prosperity. Perfect for beginners.',
    sku: 'PLT-MP-001',
    basePrice: 199,
    compareAtPrice: 299,
    images: ['/products/money-plant-1.jpg', '/products/money-plant-2.jpg'],
    tags: ['indoor', 'air-purifying', 'easy-care', 'lucky'],
    careInstructions: 'Water when soil is dry. Indirect sunlight. Trim regularly for bushy growth.',
    sunlightRequirement: 'PARTIAL_SHADE',
    waterRequirement: 'MODERATE',
    isMedicinal: false,
    variants: [
      { name: 'Small (4" pot)', sku: 'PLT-MP-001-S', price: 199, inventory: 100 },
      { name: 'Medium (6" pot)', sku: 'PLT-MP-001-M', price: 349, inventory: 75 },
      { name: 'Large (8" pot)', sku: 'PLT-MP-001-L', price: 549, inventory: 50 },
    ],
  },
  {
    name: 'Snake Plant (Sansevieria)',
    slug: 'snake-plant-sansevieria',
    categorySlug: 'indoor-plants',
    description: 'Tough, architectural plant that thrives on neglect. Excellent air purifier.',
    sku: 'PLT-SP-002',
    basePrice: 249,
    compareAtPrice: 399,
    images: ['/products/snake-plant-1.jpg'],
    tags: ['indoor', 'air-purifying', 'low-maintenance'],
    careInstructions: 'Water sparingly. Tolerates low light. Very hardy plant.',
    sunlightRequirement: 'PARTIAL_SHADE',
    waterRequirement: 'LOW',
    isMedicinal: false,
    variants: [
      { name: 'Small', sku: 'PLT-SP-002-S', price: 249, inventory: 80 },
      { name: 'Medium', sku: 'PLT-SP-002-M', price: 449, inventory: 60 },
    ],
  },
  {
    name: 'Peace Lily',
    slug: 'peace-lily',
    categorySlug: 'indoor-plants',
    description: 'Beautiful flowering plant with glossy leaves. NASA approved air purifier.',
    sku: 'PLT-PL-003',
    basePrice: 299,
    compareAtPrice: 499,
    images: ['/products/peace-lily-1.jpg'],
    tags: ['indoor', 'flowering', 'air-purifying'],
    careInstructions: 'Keep soil moist. Indirect bright light. Mist leaves regularly.',
    sunlightRequirement: 'PARTIAL_SHADE',
    waterRequirement: 'HIGH',
    isMedicinal: false,
    variants: [
      { name: 'Standard', sku: 'PLT-PL-003-S', price: 299, inventory: 50 },
    ],
  },

  // Medicinal Plants
  {
    name: 'Aloe Vera Plant',
    slug: 'aloe-vera-plant',
    categorySlug: 'medicinal-plants',
    description: 'Miracle plant with healing properties. Great for skin care and burns.',
    sku: 'PLT-AV-004',
    basePrice: 149,
    compareAtPrice: 249,
    images: ['/products/aloe-vera-1.jpg'],
    tags: ['medicinal', 'succulent', 'easy-care'],
    careInstructions: 'Water once a week. Bright indirect light. Well-draining soil.',
    sunlightRequirement: 'FULL_SUN',
    waterRequirement: 'LOW',
    isMedicinal: true,
    variants: [
      { name: 'Small', sku: 'PLT-AV-004-S', price: 149, inventory: 120 },
      { name: 'Large', sku: 'PLT-AV-004-L', price: 299, inventory: 80 },
    ],
  },
  {
    name: 'Tulsi (Holy Basil)',
    slug: 'tulsi-holy-basil',
    categorySlug: 'medicinal-plants',
    description: 'Sacred plant with medicinal properties. Boosts immunity and reduces stress.',
    sku: 'PLT-TB-005',
    basePrice: 99,
    compareAtPrice: 149,
    images: ['/products/tulsi-1.jpg'],
    tags: ['medicinal', 'herb', 'outdoor'],
    careInstructions: 'Water daily. Full sunlight. Pinch tips for bushy growth.',
    sunlightRequirement: 'FULL_SUN',
    waterRequirement: 'HIGH',
    isMedicinal: true,
    variants: [
      { name: 'Single Plant', sku: 'PLT-TB-005-S', price: 99, inventory: 150 },
    ],
  },

  // Flowering Plants
  {
    name: 'Rose Plant - Red',
    slug: 'rose-plant-red',
    categorySlug: 'flowering-plants',
    description: 'Classic red roses perfect for your garden. Fragrant blooms.',
    sku: 'PLT-RS-006',
    basePrice: 349,
    compareAtPrice: 499,
    images: ['/products/rose-red-1.jpg'],
    tags: ['flowering', 'outdoor', 'fragrant'],
    careInstructions: 'Water regularly. Full sunlight. Fertilize monthly during growing season.',
    sunlightRequirement: 'FULL_SUN',
    waterRequirement: 'HIGH',
    isMedicinal: false,
    variants: [
      { name: 'Grafted Plant', sku: 'PLT-RS-006-G', price: 349, inventory: 40 },
    ],
  },
  {
    name: 'Marigold Plant',
    slug: 'marigold-plant',
    categorySlug: 'flowering-plants',
    description: 'Bright orange flowers. Natural pest repellent for vegetable gardens.',
    sku: 'PLT-MG-007',
    basePrice: 79,
    compareAtPrice: 129,
    images: ['/products/marigold-1.jpg'],
    tags: ['flowering', 'outdoor', 'pest-repellent'],
    careInstructions: 'Water moderately. Full sun to partial shade. Deadhead spent blooms.',
    sunlightRequirement: 'FULL_SUN',
    waterRequirement: 'MODERATE',
    isMedicinal: false,
    variants: [
      { name: 'Pack of 3', sku: 'PLT-MG-007-P3', price: 199, inventory: 60 },
      { name: 'Pack of 6', sku: 'PLT-MG-007-P6', price: 349, inventory: 40 },
    ],
  },

  // Seeds
  {
    name: 'Tomato Seeds - Hybrid',
    slug: 'tomato-seeds-hybrid',
    categorySlug: 'vegetable-seeds',
    description: 'High yielding hybrid tomato seeds. Perfect for home gardens.',
    sku: 'SED-TM-008',
    basePrice: 49,
    compareAtPrice: 79,
    images: ['/products/tomato-seeds-1.jpg'],
    tags: ['seeds', 'vegetable', 'hybrid'],
    careInstructions: 'Sow in seedling tray. Transplant after 3-4 weeks. Full sunlight required.',
    sunlightRequirement: 'FULL_SUN',
    waterRequirement: 'MODERATE',
    isMedicinal: false,
    variants: [
      { name: '10g Pack', sku: 'SED-TM-008-10G', price: 49, inventory: 200 },
      { name: '50g Pack', sku: 'SED-TM-008-50G', price: 199, inventory: 100 },
    ],
  },
  {
    name: 'Sunflower Seeds',
    slug: 'sunflower-seeds',
    categorySlug: 'flower-seeds',
    description: 'Giant sunflower variety. Grows up to 8 feet tall.',
    sku: 'SED-SF-009',
    basePrice: 39,
    images: ['/products/sunflower-seeds-1.jpg'],
    tags: ['seeds', 'flower', 'tall'],
    careInstructions: 'Direct sow in ground. Full sunlight. Water regularly.',
    sunlightRequirement: 'FULL_SUN',
    waterRequirement: 'MODERATE',
    isMedicinal: false,
    variants: [
      { name: '20 Seeds', sku: 'SED-SF-009-20', price: 39, inventory: 150 },
    ],
  },

  // Fertilizers
  {
    name: 'Organic Vermicompost - 5kg',
    slug: 'organic-vermicompost-5kg',
    categorySlug: 'vermicompost',
    description: 'Premium quality vermicompost rich in nutrients. 100% organic.',
    sku: 'FRT-VC-010',
    basePrice: 249,
    compareAtPrice: 349,
    images: ['/products/vermicompost-1.jpg'],
    tags: ['organic', 'fertilizer', 'soil-amendment'],
    careInstructions: 'Mix with potting soil or use as top dressing.',
    isMedicinal: false,
    variants: [
      { name: '5kg Pack', sku: 'FRT-VC-010-5KG', price: 249, inventory: 100 },
      { name: '10kg Pack', sku: 'FRT-VC-010-10KG', price: 449, inventory: 80 },
    ],
  },
  {
    name: 'NPK Fertilizer 19:19:19',
    slug: 'npk-fertilizer-19-19-19',
    categorySlug: 'chemical-fertilizers',
    description: 'Balanced NPK fertilizer for all plants. Water soluble.',
    sku: 'FRT-NPK-011',
    basePrice: 149,
    images: ['/products/npk-fertilizer-1.jpg'],
    tags: ['fertilizer', 'chemical', 'water-soluble'],
    careInstructions: 'Dissolve in water as per instructions. Apply every 2 weeks.',
    isMedicinal: false,
    variants: [
      { name: '500g', sku: 'FRT-NPK-011-500G', price: 149, inventory: 120 },
      { name: '1kg', sku: 'FRT-NPK-011-1KG', price: 249, inventory: 90 },
    ],
  },

  // Pots & Planters
  {
    name: 'Ceramic Pot - White',
    slug: 'ceramic-pot-white',
    categorySlug: 'ceramic-pots',
    description: 'Premium white ceramic pot with drainage hole. Modern design.',
    sku: 'POT-CER-012',
    basePrice: 299,
    compareAtPrice: 499,
    images: ['/products/ceramic-pot-white-1.jpg'],
    tags: ['pot', 'ceramic', 'indoor'],
    isMedicinal: false,
    variants: [
      { name: '4 inch', sku: 'POT-CER-012-4IN', price: 299, inventory: 50 },
      { name: '6 inch', sku: 'POT-CER-012-6IN', price: 449, inventory: 40 },
      { name: '8 inch', sku: 'POT-CER-012-8IN', price: 649, inventory: 30 },
    ],
  },
  {
    name: 'Self Watering Planter',
    slug: 'self-watering-planter',
    categorySlug: 'self-watering-pots',
    description: 'Smart planter with water reservoir. Water plants last up to 2 weeks.',
    sku: 'POT-SW-013',
    basePrice: 549,
    compareAtPrice: 799,
    images: ['/products/self-watering-pot-1.jpg'],
    tags: ['pot', 'self-watering', 'smart'],
    isMedicinal: false,
    variants: [
      { name: 'Small', sku: 'POT-SW-013-S', price: 549, inventory: 35 },
      { name: 'Large', sku: 'POT-SW-013-L', price: 849, inventory: 25 },
    ],
  },

  // Garden Tools
  {
    name: 'Garden Tool Set - 5 Pieces',
    slug: 'garden-tool-set-5-pieces',
    categorySlug: 'hand-tools',
    description: 'Complete set of essential gardening tools. Includes trowel, fork, rake, weeder, and transplanter.',
    sku: 'TOOL-SET-014',
    basePrice: 399,
    compareAtPrice: 599,
    images: ['/products/tool-set-1.jpg'],
    tags: ['tools', 'set', 'essential'],
    isMedicinal: false,
    variants: [
      { name: 'Standard Set', sku: 'TOOL-SET-014-STD', price: 399, inventory: 60 },
    ],
  },
  {
    name: 'Watering Can - 5 Liter',
    slug: 'watering-can-5-liter',
    categorySlug: 'watering-tools',
    description: 'Durable plastic watering can with long spout for easy watering.',
    sku: 'TOOL-WC-015',
    basePrice: 199,
    images: ['/products/watering-can-1.jpg'],
    tags: ['tools', 'watering'],
    isMedicinal: false,
    variants: [
      { name: '5 Liter', sku: 'TOOL-WC-015-5L', price: 199, inventory: 70 },
    ],
  },
];

export const banners = [
  {
    title: 'Welcome to Nurtury',
    description: 'India\'s Largest Online Plant Nursery',
    image: '/banners/banner-1.jpg',
    link: '/products',
    order: 1,
  },
  {
    title: 'Monsoon Special',
    description: 'Upto 40% off on all plants',
    image: '/banners/banner-2.jpg',
    link: '/products?sale=true',
    order: 2,
  },
  {
    title: 'New Arrivals',
    description: 'Exotic plants collection',
    image: '/banners/banner-3.jpg',
    link: '/products?sort=newest',
    order: 3,
  },
];

export const coupons = [
  {
    code: 'WELCOME10',
    description: 'Welcome offer - 10% off on first order',
    discountType: 'PERCENTAGE',
    discountValue: 10,
    minPurchaseAmount: 500,
    maxDiscountAmount: 200,
    usageLimit: 1000,
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2025-12-31'),
  },
  {
    code: 'SAVE100',
    description: 'Flat Rs. 100 off on orders above Rs. 999',
    discountType: 'FIXED',
    discountValue: 100,
    minPurchaseAmount: 999,
    usageLimit: 500,
    validFrom: new Date('2024-01-01'),
    validUntil: new Date('2025-12-31'),
  },
  {
    code: 'MONSOON20',
    description: 'Monsoon sale - 20% off',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minPurchaseAmount: 1000,
    maxDiscountAmount: 500,
    validFrom: new Date('2024-06-01'),
    validUntil: new Date('2024-09-30'),
  },
];

